# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "exfat" ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-daeeb3f7-0a3d-4d24-b864-31819d24bdc8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-daeeb3f7-0a3d-4d24-b864-31819d24bdc8".device = "/dev/disk/by-uuid/daeeb3f7-0a3d-4d24-b864-31819d24bdc8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/73CB-D25D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/usbnas" = {
    device = "dev/disk/by-uuid/CCC6-D555";
    fsType = "exfat-fuse";
    options = [ "defaults" "nofail" "uid=0" "gid=0" "umask=0000"];
  };

  swapDevices =
    [ { device = "/dev/mapper/luks-3814ed9e-6071-412b-93d0-5d142531a483"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
